# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Cheng-Chi (Kirin) Chang # Website name
baseURL: 'https://kirinchang.com/' # Website URL

############################
## LANGUAGE
############################

defaultContentLanguage: en

en:
  languageCode: en-us
  contentDir: content/en
zh:
  languageCode: zh-T
  contentDir: content/zh
  title: Academic
  params:
    description: Site description in Chinese...
  menu:
    main:
      - name: 首頁
        url: '#about'
        weight: 10
      - name: 文章
        url: '#posts'
        weight: 20
      - name: 項目
        url: '#projects'
        weight: 30
      - name: 論文
        url: '#featured'
        weight: 40
      - name: 與我聯絡
        url: '#contact'
        weight: 60
      - name: 課程
        url: courses/
        weight: 80
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
