# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
zh-hant:
  languageCode: zh-hant
  contentDir: content/zh-hant
  languageName: "繁體中文"
  title: 張正麒
  params:
    description: Site description in Chinese...
  menu:
    main:
      - name: 首頁
        url: '#about'
        weight: 10
      - name: 文章
        url: '#posts'
        weight: 20
      - name: 項目
        url: '#projects'
        weight: 30
      - name: 論文
        url: '#featured'
        weight: 40
      - name: 與我聯絡
        url: '#contact'
        weight: 60
      - name: 課程
        url: courses/
        weight: 80

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
